---
name: CICD
on:
  push:
    branches:
      - main
  pull_request:

env:
  MKDOCS_MATERIAL_VER: 7.2.2

jobs:
  docs-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker run -v $(pwd):/docs --entrypoint mkdocs squidfunk/mkdocs-material:$MKDOCS_MATERIAL_VER build --clean --strict
      - name: htmltest
        run: |
          curl https://htmltest.wjdp.uk | bash
          ./bin/htmltest -c docs/htmltest.yml

  publish:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: docs-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: docker run -v $(pwd):/docs --entrypoint mkdocs squidfunk/mkdocs-material:$MKDOCS_MATERIAL_VER gh-deploy --force --strict
